[DEV-5570] IDV Award Amounts Section: show award/child award covid data in both tabs in table view
fedspendingtransparency/usaspending-website pull request #2087
Opened 2020-09-14 21:03 UTC by MaxwellKendall

**High level description:**
For IDVs, we show data for both `the idv itself` and the idv's child awards. If either the award itself or any of the children has file-c covid spending data, we want to show rows in the table for both tabs

**Technical details:**
- Restoring tests for relevant container (they weren't executing because the file wasn't appended with `-test`)
- Removing superfluous component `AwardAmounts`
- Making call for child award amount data and award amount data for the award itself in the same container. This makes it easier to see what's going on.
- Updating `showFileC` boolean logic to show fileC data in the table if either child covid data exists or if it exists on the parent award.

**JIRA Ticket:**
[DEV-5570](https://federal-spending-transparency.atlassian.net/browse/DEV-5570)

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
`N/A` Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
`N/A`Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
`N/A`Verified mobile/tablet/desktop/monitor responsiveness
`N/A`Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
`N/A`Added Unit Tests for methods in Container Components, reducers, helper functions, and models `if applicable`
`N/A`All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3277](https://federal-spending-transparency.atlassian.net/browse/DEV-3277)
`N/A`[API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
`N/A`[Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
`N/A`Design review complete `if applicable`
`N/A`[API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2020-09-17 16:57 UTC, jonhill13 requested changes

2020-09-17 16:57 UTC, jonhill13 commented on src/js/containers/award/idv/IdvAwardAmountsSectionContainer.jsx
> +    thisIdvHasFileC: PropTypes.bool
Do we still need this prop considering it looks like we are setting it below?

2020-09-21 14:59 UTC, jameslee40 approved these changes

2020-09-21 15:02 UTC, jameslee40 approved these changes

2020-09-21 17:17 UTC, nelsonbbarriento23 approved these changes

2020-09-22 14:29 UTC, jonhill13 approved these changes

2020-09-22 14:29 UTC, merged