[DEV-6355] GA Pageview title logging bug
fedspendingtransparency/usaspending-website pull request #2214
Opened 2020-11-09 14:12 UTC by afnazu

**High level description:**

This PR addresses the bug in production with GA logging mismatched page titles

**Technical details:**

Moving pageview firing logic to `MetaTags.jsx` so that the pageview event is fired only after the correct page title has been generated

**JIRA Ticket:**
[DEV-6355](https://federal-spending-transparency.atlassian.net/browse/DEV-6355)

**Mockup:**
N/A

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2020-11-09 14:24 UTC, MaxwellKendall requested changes

2020-11-09 14:24 UTC, MaxwellKendall commented on src/js/helpers/analytics/Analytics.js
> +    pageview(pathname, pagename) {
Lets do this same thing w/ our logging in production w/o gtm.

2020-11-09 20:32 UTC, afnazu commented on src/js/helpers/analytics/Analytics.js
> +            this._execute(
that was my initial thought too - but after testing on GA i saw that it was still displaying mismatched page titles. I found this documentation that shows adding the set command as a new ga() call -> https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications

2020-11-09 21:39 UTC, MaxwellKendall approved these changes

2020-11-09 21:40 UTC, MaxwellKendall commented
@afnazu can you demo this tomorrow?

2020-11-13 21:20 UTC, MaxwellKendall requested changes

2020-11-13 21:20 UTC, MaxwellKendall commented on src/js/components/sharedComponents/metaTags/MetaTags.jsx
> +            Analytics.pageview(pathname, this.props.og_title);
this should just go in component did mount

2020-11-13 21:55 UTC, MaxwellKendall approved these changes

2020-11-13 22:09 UTC, merged