[OPS-1636] Redirect-Config.json file for Changes in OPS Land to redirect state/01 --> state/alabama via 301
fedspendingtransparency/usaspending-website pull request #2377
Opened 2021-02-05 18:18 UTC by MaxwellKendall

**High level description:**
OPS will consume this file to redirect our state URLS at the network level incase someone goes directly to `/state/01`. [New deploy script](https://github.com/fedspendingtransparency/usaspending-config/pull/1001) will generate and consume this file.

**Technical details:**
- build script to generate .json
- build config updated to expect .json file to exist in root directory, and copy into build artifact `/public` dir
- new npm script for deploy script in usaspending-config to use

**JIRA Ticket:**
[OPS-1636](https://federal-spending-transparency.atlassian.net/browse/OPS-1636)

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
`N/A` Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
`N/A` Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
`N/A` Verified mobile/tablet/desktop/monitor responsiveness
`N/A` Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
`N/A` Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
`N/A`  [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
`N/A` [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`
- [ ] Tested in sandbox

Reviewer(s):
`N/A`  Design review complete `if applicable`
`N/A`  [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete
- [ ] OPS code review complete @bminahan-kc

2021-02-05 19:59 UTC, bminahan-kc approved these changes
👍

2021-02-09 15:34 UTC, bminahan-kc requested changes
looks like state redirects are fine but the legacy ones also need that change

2021-02-09 15:34 UTC, bminahan-kc commented on scripts/buildRedirectConfig.js
> +    "/^Pages/Default.aspx/": "/#",
^/Pages/Default.aspx

2021-02-09 15:34 UTC, bminahan-kc commented on scripts/buildRedirectConfig.js
> +    "/^Pages/AdvancedSearch.aspx/": "/search",
^/Pages/AdvancedSearch.aspx

2021-02-09 15:34 UTC, bminahan-kc commented on scripts/buildRedirectConfig.js
> +    "/^DownloadCenter/Pages/DataDownload.aspx/": "/download_center/custom_award_data",
^/DownloadCenter/Pages/DataDownload.aspx

2021-02-09 15:34 UTC, bminahan-kc commented on scripts/buildRedirectConfig.js
> +    "/^DownloadCenter/Pages/dataarchives.aspx/": "/download_center/award_data_archive",
^/DownloadCenter/Pages/dataarchives.aspx

2021-02-09 15:34 UTC, bminahan-kc commented on scripts/buildRedirectConfig.js
> +    "/^covid-19/": "/disaster/covid-19"
^/covid-19

2021-02-11 18:01 UTC, bminahan-kc approved these changes

2021-02-12 15:34 UTC, ebdabbs approved these changes

2021-02-16 19:36 UTC, merged