[OPS-1780] moving selenium tests into frontend code repositories
fedspendingtransparency/usaspending-website pull request #2536
Opened 2021-04-29 21:05 UTC by bminahan-kc

- adding USAspending selenium tests to frontend code repository
- iterating dockerfile

2021-04-30 15:45 UTC, gpontejos approved these changes

2021-04-30 16:04 UTC, MaxwellKendall requested changes
This would be a huge change. I am personally against this.

2021-04-30 20:47 UTC, ebdabbs commented
@bminahan-kc & @MaxwellKendall I put a meeting on the calendar for Monday so we can discuss further. I will leave this PR open, but let's hold off on merging. Thanks!

2021-05-03 15:24 UTC, bminahan-kc commented
we will not be doing this after meeting with frontend

2021-05-03 15:24 UTC, closed without merging