Dev-8516 homepage 'Getting Started' Section Layout
fedspendingtransparency/usaspending-website pull request #2987
Opened 2022-03-28 13:11 UTC by afnazu

**High level description:**

Implement Getting Started section layout as part of homepage update

**JIRA Ticket:**
[DEV-8516](https://federal-spending-transparency.atlassian.net/browse/DEV-8516)

**Mockup:**
See ticket for link

The following are ALL required for the PR to be merged:

Author:
- [ ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2022-03-30 15:14 UTC, anjenkin requested changes
Just a couple comments.  Also I think we could add a unit test to check for the existence of content, though doesn't need to be done here but with the corresponding content ticket.

2022-03-31 14:23 UTC, anjenkin commented
@afnazu One more thing.  I just double checked with the designers, and we should switch to the mobile view at < 992.  This layout is currently switch to mobile at < 768.

2022-03-31 21:11 UTC, afnazu commented on src/js/components/homepageUpdate/gettingStarted/GettingStarted.jsx
> +                        <h5>A big-picture view of government spending</h5>
Updated to use <h2> and <h3> organization! I had this updated in the follow up content branch but just updated here for consistency

2022-03-31 21:12 UTC, afnazu commented on src/js/components/homepageUpdate/gettingStarted/GettingStarted.jsx
> +                    <button>Select Search Type</button>
I opened a PR for DEV-8550 which addresses this, once that is merged the existing <button> element will use the updated common style

2022-04-04 16:27 UTC, anjenkin approved these changes

2022-04-04 16:27 UTC, merged