DEV-8767 hover modifications
fedspendingtransparency/usaspending-website pull request #3094
Opened 2022-05-26 15:42 UTC by nick-torres

**High level description:**

Fix tooltip disappearing, add outlay amount to tooltip, move tooltip closer to cursor

**Technical details:**

added listener on svg to remove tooltip
added outlay amount to data model and added it to the hover
changed the transform to move the tooltip closer

**JIRA Ticket:**
[DEV-8767](https://federal-spending-transparency.atlassian.net/browse/DEV-8767)

**Mockup:**
https://invis.io/RYA3XN5WP#/273832670_Homepage_2-2_E

The following are ALL required for the PR to be merged:

Author:
- [ ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2022-06-03 19:39 UTC, anjenkin requested changes
Looks good for the most part.  The only issue is that the outlay tooltip is still staying open when moving the cursor away from the chart

https://user-images.githubusercontent.com/121010/171938110-a10e17e7-543e-4253-bc43-9e56c16542c5.mov

.

2022-06-03 22:59 UTC, nick-torres commented
@anjenkin i thought that's what 

```
svg.select('#sof_chart').on('mouseleave', () => {
                setIsHovered(false);
                setHoverData(null);
                svg.selectAll('#bar-tooltip').remove();
            });
```

would solve

did i implement that wrong? or put it in the wrong place?

2022-06-06 13:48 UTC, anjenkin commented
@nick-torres Yes that worked for some other d3 charts.  Double check the donut chart on the agency profile page - https://github.com/fedspendingtransparency/usaspending-website/blob/eac855dc530d5378ac3cc288b5a3f90f7d6e8463/src/js/components/agency/visualizations/ObligationsByAwardType.jsx#L95

I think you could do some more debugging to determine if/when this event is triggered.  Also, there should be a controlled prop on the Tooltip wrapper that hides and shows the tooltip on hover.  Similar to here - https://github.com/fedspendingtransparency/usaspending-website/blob/eac855dc530d5378ac3cc288b5a3f90f7d6e8463/src/js/components/agency/visualizations/ObligationsByAwardType.jsx#L265

2022-06-07 10:43 UTC, anjenkin approved these changes

2022-06-07 10:43 UTC, merged