DEV-8850 updates to sidebar to prevent wrong section chosen
fedspendingtransparency/usaspending-website pull request #3131
Opened 2022-06-30 14:38 UTC by nick-torres

**High level description:**

Update Training Banner so that learn more links to new section of about page

**Technical details:**

changes to Sidebar code to choose the right section based on the page location

**JIRA Ticket:**
[DEV-8850](https://federal-spending-transparency.atlassian.net/browse/DEV-8850)

The following are ALL required for the PR to be merged:

Author:
- [ ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2022-06-30 19:45 UTC, anjenkin requested changes
seems to work through ui testing.  please see code comments below

2022-06-30 19:49 UTC, nick-torres commented on src/js/components/sharedComponents/sidebar/Sidebar.jsx
> -        if (typeof detectActiveSection === 'function') detectActiveSection(nextActiveSection);
i misinterpreted it before - it was either a boolean or a function (i didn't end up changing the prop type)

2022-06-30 19:49 UTC, nick-torres commented on src/js/components/about/TrainingContent.jsx
> +                            href="https://www.surveymonkey.com/r/YK963LJ">
good call i'll check now

2022-06-30 19:53 UTC, nick-torres commented on src/js/components/about/AboutContent.jsx
> -            return;
added back in

2022-06-30 19:53 UTC, nick-torres commented on src/js/components/sharedComponents/sidebar/Sidebar.jsx
> -        if (typeof detectActiveSection === 'function') detectActiveSection(nextActiveSection);
whether it was bool or a func it def needed to be present though, otherwise the sidebar would go haywire

2022-07-01 13:02 UTC, nick-torres commented on src/js/components/about/TrainingContent.jsx
> +                            href="https://www.surveymonkey.com/r/YK963LJ">
done

2022-07-01 14:34 UTC, merged