DEV-8976 fixed xxx is not a function test
fedspendingtransparency/usaspending-website pull request #3210
Opened 2022-08-29 21:49 UTC by nick-torres

**High level description:**

fixed error with jest tests
**Technical details:**

a function was not mocked when it should have been

**JIRA Ticket:**
[DEV-8976](https://federal-spending-transparency.atlassian.net/browse/DEV-8976)

The following are ALL required for the PR to be merged:

Author:
- [ ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2022-08-30 14:46 UTC, anjenkin requested changes
A comment and question inline - 
1) Are you getting this error when running this branch locally?
ERROR in ./index.js
Module build failed: Error: Keyword [object Object] is not a valid identifier
    at Ajv.addKeyword (/Users/andreablackwell/code/usaspending-website/node_modules/babel-loader/node_modules/ajv/lib/keyword.js:30:11)

2) Is this ticket ready to merge?  It's marked as ready for review but still has the do not merge label

2022-08-30 18:08 UTC, nick-torres commented on tests/containers/award/idv/IdvActivityContainer-test.jsx
> -        const container = shallow(<IdvActivityContainer awardId="1234" />);
the first test failed and didn't use shallow if i remember correctly so i don't think it was that

2022-08-30 18:11 UTC, nick-torres commented on tests/containers/award/idv/IdvActivityContainer-test.jsx
> -        const container = shallow(<IdvActivityContainer awardId="1234" />);
misread - i don't know if changing it from shallow made a difference, i tried to make it look like the first test i can't remember if it was still failing after i got the first test to pass

2022-08-31 10:49 UTC, anjenkin approved these changes

2022-08-31 10:50 UTC, merged