MOD- 9204 Sticky top bar bg color
fedspendingtransparency/usaspending-website pull request #3300
Opened 2022-10-31 17:08 UTC by chasls2

**High level description:**

Updated the colors of the sticky bar

**Technical details:**

Updated the CSS files to match mocks from zeplin inside of the data-trans epo

**JIRA Ticket:**
[DEV-9204](https://federal-spending-transparency.atlassian.net/browse/DEV-9204)

**Mockup:**
https://invis.io/RYA3XN5WP#/273832670_Homepage_2-2_E

The following are ALL required for the PR to be merged:

Author:
- [ ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2022-11-02 18:31 UTC, chasls2 commented
Updated the Color of the mobile lower sticky bar

2022-11-02 19:32 UTC, anjenkin requested changes
Looks good.  There's just a 1 off error at 992px for the desktop background color.  The tablet breakpoint should be from 768 to 991.  992 should still be desktop - 

![Screen Shot 2022-11-02 at 3 31 23 PM](https://user-images.githubusercontent.com/121010/199585727-40895a08-0c26-4bdd-8441-ada9e565c8cd.png)

2022-11-02 20:10 UTC, chasls2 commented
![image](https://user-images.githubusercontent.com/110061741/199591811-fc36d016-3edd-43bc-9acf-49b04e1fc319.png)

this is the preset breakpoints medium changes over at 992. So you want me to do the tablet-screen?

2022-11-04 00:01 UTC, anjenkin approved these changes

2022-11-04 00:01 UTC, merged