tooltip position moved to the right
fedspendingtransparency/usaspending-website pull request #3544
Opened 2023-03-23 17:37 UTC by chasls2

**High level description:**

change the tooltip  position to the right on the searchbar component 
**Technical details:**

**JIRA Ticket:**
[DEV-9544](https://federal-spending-transparency.atlassian.net/browse/DEV-9544)

The following are ALL required for the PR to be merged:

Author:
- [ ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2023-03-23 18:15 UTC, anjenkin requested changes
This looks good on mobile and larger desktop views.  But there are tablet and small desktop views where the tooltip isn't correctly aligned with the icon.

<img width="825" alt="Screenshot 2023-03-23 at 2 13 19 PM" src="https://user-images.githubusercontent.com/121010/227308394-e23560cd-ee16-43d7-9084-a556b6829f9f.png">

2023-03-23 18:20 UTC, chasls2 commented
That means I will need to write out a isMobile function then. cause left. you can access the tooltip easily on desktop or larger. it disappears before reaching it

2023-03-28 15:51 UTC, anjenkin requested changes
Per standup this morning we're waiting to review with designers again tomorrow morning once Marcy returns.  However I played around with the code a bit.

in the searchSidebar.scss this still left: rem(-13) !important is throwing off the position of the tooltip.  It looks better when I tried -
```
                    .tooltip-spacer {
                        @media (max-width: $medium-screen) {
                            top: 90px;
                            left: 250px;
                        }
                    }
```

And in SearchSidebar.jsx changing the tooltipDirection function to the following - 
```
    const tooltipDirection = () => {
        if (window.innerWidth <= mediumScreen) {
            return "bottom";
        }
        return "right";
    };
```

The tooltip position is absolute so its relative to the document and there shouldn't be a reason to use negative values. https://developer.mozilla.org/en-US/docs/Web/CSS/position

2023-03-30 14:59 UTC, anjenkin approved these changes

2023-03-30 14:59 UTC, merged