Mod 10049 Congressional District "90"
fedspendingtransparency/usaspending-website pull request #3734
Opened 2023-07-24 16:31 UTC by chasls2

**High level description:**

Added the 90 Congressional district to state that it applies

**JIRA Ticket:**
[DEV-10049](https://federal-spending-transparency.atlassian.net/browse/DEV-10049)

**Mockup:**
https://invis.io/RYA3XN5WP#/273832670_Homepage_2-2_E

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [x] Verified mobile/tablet/desktop/monitor responsiveness
- [x] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2023-07-24 19:21 UTC, chasls2 commented
@anjenkin added Montana

2023-07-25 13:56 UTC, chasls2 commented
All districts updated

2023-07-25 14:11 UTC, anjenkin commented on src/data/congressional/original/ok_districts.json
> +            "name": "OK-90"
There are now two district "90"s here.  This first one should be changed back to "05"

2023-07-25 14:12 UTC, anjenkin requested changes
See typo inline

2023-07-25 14:14 UTC, anjenkin approved these changes

2023-07-25 14:23 UTC, chasls2 commented
Looking at the build now

2023-07-25 15:09 UTC, merged