Mod/10711 share icon position absolute
fedspendingtransparency/usaspending-website pull request #4027
Opened 2024-03-26 21:50 UTC by brianpetway

**High level description:**

Improve the situation with the placement of the copy confirmation messages

**Technical details:**

Made some css changes in dtui, made the default css to position the copy confirmation message work with the instances in the stickyHeader, other instances will require css overrides in usas

**JIRA Ticket:**
[DEV-10711](https://federal-spending-transparency.atlassian.net/browse/DEV-10711)

**Mockup:**
n/a

The following are ALL required for the PR to be merged:

Author:
- [ x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2024-03-27 17:31 UTC, anjenkin requested changes
The copy confirmation doesn't look absolute positioned and causes the share icon to shift.  Am I missing something - 

https://github.com/fedspendingtransparency/usaspending-website/assets/121010/ae62d5c2-a91e-48e8-8677-b2095a3896f0

2024-03-27 17:55 UTC, brianpetway commented
This is part of what was confusing me about this ticket earlier.
It wasn't doing that behavior when I did the work initially, but then started behaving that way while there was some weirdness happening with package-lock and the link fn.
But yesterday the package-lock and link problems stopped, so I thought it was fine.
Let me check again.

2024-03-27 18:30 UTC, brianpetway commented
Ok, I made a change in dtui and it should be fixed now.
Turns out the position absolute is needed on the confirmation class.
As well as position relative on the parent.
It's ready to review again.

2024-03-28 23:42 UTC, anjenkin approved these changes

2024-03-28 23:42 UTC, merged