Mod/10886 new table section
fedspendingtransparency/usaspending-website pull request #4075
Opened 2024-05-08 14:52 UTC by brianpetway

**High level description:**

Add the Award Table section to the new search results page

**Technical details:**

Removed the temp component and added the results table, now using dtui Table

**JIRA Ticket:**
[DEV-10886](https://federal-spending-transparency.atlassian.net/browse/DEV-10886)

**Mockup:**
https://invis.io/RYA3XN5WP#/273832670_Homepage_2-2_E

The following are ALL required for the PR to be merged:

Author:
- [x ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2024-05-22 20:54 UTC, anjenkin requested changes
table looks good.  see comments inline.  qat needs to be merged into this branch so it's clear what the pr changed from the latest

2024-05-22 20:54 UTC, anjenkin commented on src/_scss/elements/_table.scss
> +        //}
can this be removed?

2024-05-22 20:54 UTC, anjenkin commented on src/_scss/pages/search/results/searchResults.scss
> +        //@import './tables';
remove?

2024-05-22 21:36 UTC, brianpetway commented on src/_scss/elements/_table.scss
> +        //}
removed

2024-05-22 21:37 UTC, brianpetway commented on src/_scss/pages/search/results/searchResults.scss
> +        //@import './tables';
removed

2024-05-22 21:41 UTC, brianpetway commented
Latest qat is merged in, no more merge conflicts, easier to see changes now

2024-05-23 00:13 UTC, anjenkin approved these changes

2024-05-23 00:13 UTC, merged