Mod/11025 loading sorting formatting map
fedspendingtransparency/usaspending-website pull request #4127
Opened 2024-06-13 19:02 UTC by jagu65

**High level description:**
Error, loading, and no data screens are all working as intended in the Map Section. The Map Section table cells have been formatted and sorting has been fixed.

**Technical details:**
New states have been created to accommodate Map Section screens. Formatting and sorting now implemented. The MapVisualization component has been moved to the containers directory and has been renamed MapSectionContainer accordingly. 

**JIRA Ticket:**
[DEV-11025](https://federal-spending-transparency.atlassian.net/browse/DEV-11025)

**Mockup:**
n/a

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [x] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2024-06-16 02:04 UTC, anjenkin requested changes
see comments inline.  also most importantly, the table doesn't update when switching between place of performance and recipient location

2024-06-17 14:28 UTC, jagu65 commented on src/js/containers/search/newResultsView/MapSectionContainer.jsx
> +            title: "perCapita",
I was matching what I had in the component. I can change back to avoid confusion.

2024-06-17 14:28 UTC, jagu65 commented on src/js/components/search/newResultsView/map/MapSection.jsx
> +import MapVisualization from "../../../../containers/search/newResultsView/MapSectionContainer";
I'll rename!

2024-06-17 16:06 UTC, jagu65 commented
> see comments inline. also most importantly, the table doesn't update when switching between place of performance and recipient location

Inline comments have been addressed and the table is now updating when dropdown is updated.

2024-06-17 19:32 UTC, merged