DEV-11081 fed account style problems
fedspendingtransparency/usaspending-website pull request #4141
Opened 2024-06-20 21:44 UTC by nick-torres

**High level description:**

the results by categories chart had a hardcoded height - which wasn't a problem on the new results page but the component was reused on the federal account page and the height on mobile was not right so i put a wrapper around it and changed the height only on mobile which fixed the problem

**JIRA Ticket:**
[DEV-11081](https://federal-spending-transparency.atlassian.net/browse/DEV-11081)

The following are ALL required for the PR to be merged:

Author:
- [ ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2024-06-30 20:30 UTC, anjenkin requested changes
Looks soo much better.  Small issue on mobile for the Spending by Prime Award bleeding outside of the left edge.
<img width="686" alt="Screenshot 2024-06-30 at 4 28 12 PM" src="https://github.com/fedspendingtransparency/usaspending-website/assets/121010/2c5515ac-adec-4b26-b226-7662def6bfe2">


<img width="886" alt="Screenshot 2024-06-30 at 4 28 29 PM" src="https://github.com/fedspendingtransparency/usaspending-website/assets/121010/893402f4-e262-413c-8b7c-db811d758c96">

2024-07-01 18:19 UTC, nick-torres commented
issue should be fixed now

2024-07-01 19:56 UTC, anjenkin commented
I'm still seeing the same issue after pulling the latest from `fix/11081` but i now see it actually looks like the y-axis line is overlapping the text the edge of the section container.
<img width="716" alt="Screenshot 2024-07-01 at 3 56 06 PM" src="https://github.com/fedspendingtransparency/usaspending-website/assets/121010/8895158c-e65c-4959-8b18-17ed338d2cb5">

2024-07-01 20:25 UTC, anjenkin approved these changes

2024-07-02 13:51 UTC, merged