Mod/11095 outlay toggle on state tree map
fedspendingtransparency/usaspending-website pull request #4158
Opened 2024-07-02 15:02 UTC by brianpetway

**High level description:**

Add Outlays toggle and 'what is this?' accordion to state page Award Breakdown section, but hidden in upper environments

**Technical details:**

Copied the toggle and accordion from the Status of Funds table; left the accordion content the same, as specified in the ticket; added code for the toggle function to change the colors, as specified in the mock, but commented out that part so the colors will remain the same in Prod for now;
I stacked these components at mobile and made them change at 768, which is slightly different than how it's handled in the SoF section, but seemed right for this instance

**JIRA Ticket:**
[DEV-11095](https://federal-spending-transparency.atlassian.net/browse/DEV-11095)

**Mockup:**
two, in ticket

The following are ALL required for the PR to be merged:

Author:
- [ x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

2024-07-08 20:21 UTC, anjenkin requested changes
looks good.  see comments inline

2024-07-08 20:21 UTC, anjenkin commented on src/js/helpers/treemapHelper.js
> +    "#A6C2CB" // loans
the color codes map to the amount from largest to smallest not the award type so we should remove these comments

2024-07-08 20:21 UTC, anjenkin commented on src/js/helpers/treemapHelper.js
> +//     "#29e1cb" // loans, $mint-cool-20v
same as above

2024-07-08 21:06 UTC, brianpetway commented
I updated those comments

2024-07-09 13:21 UTC, anjenkin approved these changes

2024-07-09 13:21 UTC, merged